<!--
 * @Author: your name
 * @Date: 2021-03-06 20:01:25
 * @LastEditTime: 2021-03-06 22:05:50
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: /fe-interview/promise/promise.html
-->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script>
    // 成功的回调函数
    // function successCallBack(result) {
    //   console.log('成功' + result)
    // }
    // 失败的毁掉函数
    // function failureCallback(error) {
    //   console.log('失败' + error)
    // }
    // const promise = doSomething()
    // const promise2 = promise.then(successCallBack, failureCallback)
    // const promise2 = doSomething().then(successCallBack, failureCallback)
    // promise2 不仅代表doSomething()函数的完成，也代表了你传入的successCallBack或者failureCallback的完成，这两个函数也可以返回一个promise对象
    // ，从而形成另一个一步操作，这样的话在promise2上新增的回调函数也会排在这个promise对象的后面。
    // 基本上每一个promise都代表了链中另一个异步过程的完成
    // 在过去要想做多重的异步操作，会导致典型的回调地狱
    // doSomething(function(result){
    //   doSomethingElse(result, function(newResult){
    //     doThirdThing(newResult, function(finalResult) {
    //       console.log('get the final result' + finalResult )
    //     }, failureCallback)
    //   }, failureCallback)
    // }, failureCallback)
    // 现在我们可以把回调绑定在promise上，形成一个promise值
    // doSomething().then(function(result){
    //   return doSomethingElse(result)
    // })
    // .then(function(newResult){
    //   return doThirdThing(newResult)
    // })
    // .then(function(finalResult) {
    //   console.log('get the final result' + finalResult )
    // })
    // .catch(failureCallback)
    // 我们也可以用箭头函数来表示
    // doSomething().then(result=> {
    //   doSomethingElse(result)
    // })
    // .then(newResult=>{
    //   doThirdThing(newResult)
    // })
    // .then(finalResult=> {
    //   console.log('get the final result' + finalResult )
    // })
    // .catch(failureCallback)
    // 注意一定要有返回值，否则，callback 将无法获取上一个 Promise 的结果。(如果使用箭头函数，() => x 比 () => { return x; } 更简洁一些，但后一种保留 return 的写法才支持使用多个语句。）。
    // catch的后续链式操作
    // 有可能在一个回调失败后继续使用链式操作，即，使用一个catch，这对于在链式操作中抛出一个失败之后，再次进行新的操作会很有用，
    // new Promise((resolve, reject) => {
    //   console.log('初始化')
    //   resolve()
    // })
    // .then(() => {
    //   throw new error('有那里不对了')
    //   console.log('执行这个')
    // })
    // .catch(() => {
    //   console.log('执行那个')
    // })
    // .then(() => {
    //   console.log('执行这个，无论前面发生了什么')
    // })
    // 输出结果：
    // 初始化
    // 执行“那个”
    // 执行“这个”，无论前面发生了什么
    // 注意：因为抛出了错误 有哪里不对了，所以前一个 执行「这个」 没有被输出。


    // 错误传递
    // 在之前的回调地狱示例中，你可能记得有 3 次 failureCallback 的调用，而在 Promise 链中只有尾部的一次调用。
    // 通常，一遇到异常抛出，浏览器就会顺着 Promise 链寻找下一个 onRejected 失败回调函数或者由 .catch() 指定的回调函数。这和以下同步代码的工作原理（执行过程）非常相似。
    // try {
    //   let result = syncDoSomething();
    //   let newResult = syncDoSomethingElse(result);
    //   let finalResult = syncDoThirdThing(newResult);
    //   console.log(`Got the final result: ${finalResult}`);
    // } catch(error) {
    //   failureCallback(error);
    // }
    // 在 ECMAScript 2017 标准的 async/await 语法糖中，这种异步代码的对称性得到了极致的体现：
    // async function foo() {
    //   try {
    //     const result = await doSomething()
    //     const newResult = await doSomethingElse(result)
    //     const finalResult = await doThirdThing(newResult)
    //     console.log(`Got the final result: ${finalResult}`);
    //   } catch (error) {
    //     failureCallback(error);
    //   }
    // }
    // 这个例子是在promise的基础上构建的，例如，doSomething

    // Promise.resolve() 和 Promise.reject() 是手动创建一个已经 resolve 或者 reject 的 Promise 快捷方法。它们有时很有用。

    // Promise.all() 和 Promise.race() 是并行运行异步操作的两个组合式工具。
    // 我们可以发起并行操作，然后等多个操作全部结束后进行下一步操作，如下：
    // Promise.all([func1(), func2(), func3()])
    // .then(([result1, result2, result3]) => { /* use result1, result2 and result3 */ });
    
    // Promise.all可以将多个Promise实例包装成一个新的Promise实例。同时，成功和失败的返回值是不同的，成功的时候返回的是一个结果数组，而失败的时候则返回最先被reject失败状态的值
    let p1 = new Promise((resolve, reject) => {
      resolve('成功了')
    })

    let p2 = new Promise((resolve, reject) => {
      resolve('success')
    })

    let p3 = Promise.reject('失败')

    Promise.all([p1, p2]).then((result) => {
      console.log(result)               //['成功了', 'success']
    }).catch((error) => {
      console.log(error)
    })

    Promise.all([p1,p3,p2]).then((result) => {
      console.log(result)
    }).catch((error) => {
      console.log(error)      // 失败了，打出 '失败'
    })
    
    let wake = (time) => {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve(`${time / 1000}秒后醒来`)
        }, time)
      })
    }

    let p4 = wake(3000)
    let p5 = wake(2000)

    Promise.all([p4, p5]).then((result) => {
      console.log(result)       // [ '3秒后醒来', '2秒后醒来' ]
    }).catch((error) => {
      console.log(error)
    })

    // 需要特别注意的是，Promise.all获得的成功结果的数组里面的数据顺序和Promise.all接收到的数组顺序是一致的，即p1的结果在前，即便p1的结果获取的比p2要晚。这带来了一个绝大的好处：在前端开发请求数据的过程中，偶尔会遇到发送多个请求并根据请求顺序获取和使用数据的场景，使用Promise.all毫无疑问可以解决这个问题。


    let p6 = new Promise((resolve, reject) => {
    setTimeout(() => {
        resolve('success')
      },1000)
    })

    let p7 = new Promise((resolve, reject) => {
      setTimeout(() => {
        reject('failed')
      }, 500)
    })

    Promise.race([p6, p7]).then((result) => {
      console.log(result)
    }).catch((error) => {
      console.log(error)  // 打开的是 'failed'
    })
    // 顾名思义，Promse.race就是赛跑的意思，意思就是说，Promise.race([p1, p2, p3])里面哪个结果获得的快，就返回那个结果，不管结果本身是成功状态还是失败状态。
  </script>
</body>
</html>